services:
  server:
    # image: faq-server:latest
    container_name: dashboard
    build: ./dashboard-service
    labels:
      co.elastic.logs/enabled: true
      co.elastic.logs/json.overwrite_keys: true
      co.elastic.logs/json.add_error_key: true
      co.elastic.logs/json.expand_keys: true
    volumes:
      - ./dashboard-service/configs/config.toml:/app/configs/config.toml
      - ./dashboard-service/migrations:/app/migrations
    environment:
      CONFIG_PATH: ${CONFIG_PATH}
      SERVER_HOST: ${SERVER_HOST}
      SERVER_PORT: ${SERVER_PORT}
      DEFAULT_API: ${DEFAULT_API}
      READ_TIMEOUT: ${READ_TIMEOUT}
      WRITE_TIMEOUT: ${WRITE_TIMEOUT}
      IDLE_TIMEOUT: ${IDLE_TIMEOUT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_SSL_MODE: ${POSTGRES_SSL_MODE}
      POSTGRES_MIGRATIONS_PATH: ${POSTGRES_MIGRATIONS_PATH}
      JWT_SECREY_KEY: ${JWT_SECREY_KEY}
      ACCESS_TOKEN_EXP: ${ACCESS_TOKEN_EXP}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
      REDIS_USER: ${REDIS_USER}
      REDIS_USER_PASSWORD: ${REDIS_USER_PASSWORD}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      OTP_MAX: ${OTP_MAX}
      OTP_EXPIRATION_TIME: ${OTP_EXPIRATION_TIME}
    ports:
      - "4400:4400"
    restart: unless-stopped
    depends_on:
      - postgres
    network_mode: host

  mail:
    # image: mail-service:latest
    container_name: mail 
    build: ./mail-service
    volumes:
      - ./mail-service/configs/config.toml:/app/configs/config.toml
      - ./mail-service/templates:/app/templates
    environment:
      CONFIG_PATH: ${CONFIG_PATH}
      SERVER_PORT: ${SERVER_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    ports:
      - "4400:4400"
    restart: unless-stopped
    depends_on:
      - postgres
    network_mode: host

  postgres:
    image: postgres:17
    container_name: postgres 
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usr -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:latest
    container_name: redis 
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    env_file:
      - .env
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
    restart: unless-stopped
    volumes:
      - redis_data:/bitnami/redis/data

  elasticsearch:
    container_name: elastic 
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.2.0"
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana 
    image: "docker.elastic.co/kibana/kibana:7.2.0"
    ports:
      - "5601:5601"

  filebeat:
    container_name: filebeat
    image: "docker.elastic.co/beats/filebeat:7.2.0"
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  elasticsearch_data:
    driver: local
